export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';

export const FETCH_TRENDING_VIDEOS = 'FETCH_TRENDING_VIDEOS';
export const FETCH_TRENDING_VIDEOS_SUCCESS = 'FETCH_TRENDING_VIDEOS_SUCCESS';
export const FETCH_TRENDING_VIDEOS_FAILURE = 'FETCH_TRENDING_VIDEOS_FAILURE';
